### ISSUE TITLE
Text on Help Freegle box obscured on mobile

### ISSUE THREAD

**Issue by chriscant** [Freegle/iznik-client#1] opened 2017-12-19 12:51 UTC
![screenshot_20171219-115530](https://user-images.githubusercontent.com/1153272/34157858-4012720c-e4bb-11e7-80a4-2bb5ef5415a4.png)

**Comment by bernhard-hofmann** [comment] 2018-01-17 11:26
Could this be because the `col-sm` column count doesn't sum to 12? Lines 10 and 27 should either use `col-sm-8` and `col-sm-4`, or `col-sm-10` and `col-sm-2` respectively.

**Comment by edwh** [comment] 2018-01-17 11:27
Could be, yes.  Perfect chance to try out our lovely new client-side 
development environment...

------ Original Message ------

**Comment by bernhard-hofmann** [comment] 2018-01-17 11:58
I'm able to download the code at work, but unable to install `npm` or push a branch. I'm having to use my phone to post here. Things will change in February though. :)

**Comment by bernhard-hofmann** [comment] 2018-02-20 12:18
Looking at the live site, I cannot reproduce this issue anymore so I'm closing it.

**Closed as completed by bernhard-hofmann** 2018-02-20 12:18 UTC

**Comment by edwh** [comment] 2018-02-20 12:20
Sorry, I forgot to tell you that I had merged your fix in.
